#.travis.yml

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run pwa

after_success:
  - firebase deploy --project cluckr-prod --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: always
