#.travis.yml

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master
    - dev

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then ng lint && ng build; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run pwa; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then firebase deploy --project cluckrdev --token $FIREBASE_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then firebase deploy --project $PROD_PROJ_NAME --token $FIREBASE_TOKEN; fi


notifications:
  email:
    on_failure: always
    on_success: always
