#.travis.yml

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - dev

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng lint && ng build

after_success:
  - firebase deploy --project cluckrdev --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: always
